"""empty message

Revision ID: a3f472b7bcb8
Revises: f9da1da02d41
Create Date: 2021-02-10 21:12:51.747105

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a3f472b7bcb8'
down_revision = 'f9da1da02d41'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('messages', 'msg_text',
               existing_type=sa.VARCHAR(length=160),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('messages', 'msg_text',
               existing_type=sa.VARCHAR(length=160),
               nullable=True)
    # ### end Alembic commands ###
